

=============================================================
Время: 2020-10-17 11:58:49.790945

Ошибка:
Command raised an exception: TypeError: 'str' object is not callable
=============================================================

=============================================================
Время: 2020-10-17 12:32:45.172220

Ошибка:
Command raised an exception: AttributeError: 'PartialEmoji' object has no attribute 'is_usable'
=============================================================

=============================================================
Время: 2020-10-17 12:41:56.320096

Ошибка:
Command raised an exception: TypeError: object of type 'NoneType' has no len()
=============================================================

=============================================================
Время: 2020-10-17 12:42:26.981079

Ошибка:
Command raised an exception: TypeError: object of type 'NoneType' has no len()
=============================================================

=============================================================
Время: 2020-10-17 12:48:19.066549

Ошибка:
Command raised an exception: NameError: name 'self' is not defined
=============================================================

=============================================================
Время: 2020-10-17 12:48:37.805422

Ошибка:
Command raised an exception: NameError: name 'self' is not defined
=============================================================

=============================================================
Время: 2020-10-17 12:48:53.215202

Ошибка:
Command raised an exception: NameError: name 'bot' is not defined
=============================================================

=============================================================
Время: 2020-10-17 12:49:03.642066

Ошибка:
Command raised an exception: NameError: name 'client' is not defined
=============================================================

=============================================================
Время: 2020-10-17 12:49:29.778673

Ошибка:
Command raised an exception: NameError: name 'self' is not defined
=============================================================

=============================================================
Время: 2020-10-17 12:56:47.645401

Ошибка:
Command raised an exception: NameError: name 'emoji' is not defined
=============================================================

=============================================================
Время: 2020-10-17 12:57:17.374876

Ошибка:
Command raised an exception: HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In content: Must be 2000 or fewer in length.
=============================================================

=============================================================
Время: 2020-10-17 12:58:18.623083

Ошибка:
You do not own this bot.
=============================================================

=============================================================
Время: 2020-10-17 12:58:24.791654

Ошибка:
You do not own this bot.
=============================================================

=============================================================
Время: 2020-10-17 13:04:32.634451

Ошибка:
Command raised an exception: ConnectTimeout: timed out
=============================================================

=============================================================
Время: 2020-10-17 13:07:34.511766

Ошибка:
Command raised an exception: AttributeError: 'NoneType' object has no attribute 'emoji'
=============================================================

=============================================================
Время: 2020-10-17 13:07:48.324817

Ошибка:
Command raised an exception: AttributeError: 'NoneType' object has no attribute 'emoji'
=============================================================

=============================================================
Время: 2020-10-17 13:10:32.054499

Ошибка:
Command raised an exception: AttributeError: 'NoneType' object has no attribute 'is_unicode_emoji'
=============================================================

=============================================================
Время: 2020-10-17 16:12:46.205847

Ошибка:
Command raised an exception: TemplateSyntaxError: Encountered unknown tag 'random'.
=============================================================

=============================================================
Время: 2020-10-17 16:37:17.513156

Ошибка:
stats_count is a required argument that is missing.
=============================================================

=============================================================
Время: 2020-10-17 16:42:46.291479

Ошибка:
Command raised an exception: TemplateSyntaxError: Encountered unknown tag 'while'.
=============================================================

=============================================================
Время: 2020-10-17 16:52:02.609928

Ошибка:
Command raised an exception: AttributeError: module 'Tools.template_engine' has no attribute 'TemplateError'
=============================================================

=============================================================
Время: 2020-10-17 17:32:26.754080

Ошибка:
Command "users" is not found
=============================================================

=============================================================
Время: 2020-10-17 17:38:43.632894

Ошибка:
Command raised an exception: TemplateSyntaxError: Encountered unknown tag 'channel'.
=============================================================

=============================================================
Время: 2020-10-17 17:39:35.754183

Ошибка:
Command raised an exception: UndefinedError: 'Tools.template_engine.Channel object' has no attribute 'send_message'
=============================================================

=============================================================
Время: 2020-10-17 17:41:36.594125

Ошибка:
Command raised an exception: AttributeError: partially initialized module 'Tools.template_engine' has no attribute 'Member' (most likely due to a circular import)
=============================================================

=============================================================
Время: 2020-10-17 17:52:32.351574

Ошибка:
Command "info" is not found
=============================================================

=============================================================
Время: 2020-10-17 17:56:18.345178

Ошибка:
Command raised an exception: ExtensionFailed: Extension 'Cogs.different' raised an error: SyntaxError: invalid syntax (different.py, line 216)
=============================================================

=============================================================
Время: 2020-10-17 17:56:22.517018

Ошибка:
Command "bot-info" is not found
=============================================================

=============================================================
Время: 2020-10-17 17:57:01.135713

Ошибка:
Command raised an exception: ExtensionNotLoaded: Extension 'Cogs.different' has not been loaded.
=============================================================

=============================================================
Время: 2020-10-17 17:57:04.939538

Ошибка:
Command "bot-info" is not found
=============================================================

=============================================================
Время: 2020-10-17 17:57:48.855082

Ошибка:
Command raised an exception: HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In embed.fields.5.name: This field is required
=============================================================

=============================================================
Время: 2020-10-17 17:58:10.425502

Ошибка:
Command raised an exception: HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In embed.fields.5.name: This field is required
=============================================================

=============================================================
Время: 2020-10-17 18:07:59.225513

Ошибка:
Command "boy-info" is not found
=============================================================