

=============================================================
Время: 2020-10-23 09:02:24.566748

Ошибка:
Command raised an exception: TypeError: unsupported operand type(s) for +=: 'int' and 'datetime.time'
=============================================================

=============================================================
Время: 2020-10-23 09:35:07.978956

Ошибка:
Command raised an exception: TypeError: float() argument must be a string or a number, not 'datetime.time'
=============================================================

=============================================================
Время: 2020-10-23 09:35:52.351296

Ошибка:
Command raised an exception: TypeError: int() argument must be a string, a bytes-like object or a number, not 'datetime.time'
=============================================================

=============================================================
Время: 2020-10-23 09:38:42.474432

Ошибка:
Command raised an exception: TypeError: int() argument must be a string, a bytes-like object or a number, not 'datetime.time'
=============================================================

=============================================================
Время: 2020-10-23 10:29:56.787037

Ошибка:
Command raised an exception: ProgrammingError: 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '%s AND guild_id = %s' at line 1
=============================================================

=============================================================
Время: 2020-10-23 15:16:06.425064

Ошибка:
Command raised an exception: DataError: 1136 (21S01): Column count doesn't match value count at row 1
=============================================================

=============================================================
Время: 2020-10-23 18:05:25.608477

Ошибка:
Command "*его" is not found
=============================================================

=============================================================
Время: 2020-10-23 18:10:31.439797

Ошибка:
Command raised an exception: SyntaxError: invalid syntax (<unknown>, line 2)
=============================================================

=============================================================
Время: 2020-10-23 18:10:54.988824

Ошибка:
Command raised an exception: SyntaxError: invalid syntax (<unknown>, line 2)
=============================================================

=============================================================
Время: 2020-10-23 18:12:00.282344

Ошибка:
You do not own this bot.
=============================================================

=============================================================
Время: 2020-10-23 18:12:09.559668

Ошибка:
Command raised an exception: SyntaxError: invalid syntax (<unknown>, line 2)
=============================================================

=============================================================
Время: 2020-10-23 18:12:54.281888

Ошибка:
You do not own this bot.
=============================================================

=============================================================
Время: 2020-10-23 20:23:53.662904

Ошибка:
Command raised an exception: AttributeError: 'str' object has no attribute 'time'
=============================================================

=============================================================
Время: 2020-10-23 20:24:35.565849

Ошибка:
Command raised an exception: ProgrammingError: 1054 (42S22): Unknown column 'id' in 'field list'
=============================================================

=============================================================
Время: 2020-10-23 20:28:39.007710

Ошибка:
Command raised an exception: DataError: 1136 (21S01): Column count doesn't match value count at row 1
=============================================================